# Generated by Django 3.1.4 on 2020-12-17 14:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.CharField(max_length=60, verbose_name='Организатор')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('link', models.SlugField(unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название направления')),
                ('number', models.TextField(blank=True, null=True, verbose_name='Код направления')),
                ('USE', models.TextField(blank=True, null=True, verbose_name='ЕГЭ')),
                ('work', models.TextField(blank=True, null=True, verbose_name='Трудоустройство')),
                ('practice', models.TextField(blank=True, null=True, verbose_name='Практика')),
                ('internship', models.TextField(blank=True, null=True, verbose_name='Стажировки')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Бюджетных мест')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена обучения')),
                ('score', models.TextField(blank=True, null=True, verbose_name='Баллы прошлых лет')),
                ('min_score', models.TextField(blank=True, null=True, verbose_name='Минимальные баллы')),
                ('disciplines_list', models.TextField(blank=True, null=True, verbose_name='Список дисциплин')),
                ('best_students', models.TextField(blank=True, null=True, verbose_name='Список дисциплин')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.event', verbose_name='Вебинар')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organization', verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Направлени',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('status', models.CharField(choices=[('parent', 'Родитель'), ('enrollee', 'Абитуриент')], max_length=10, verbose_name='Статус')),
                ('SNILS', models.IntegerField(null=True, verbose_name='СНИЛС')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
