# Generated by Django 3.1.4 on 2021-01-15 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='achievements', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='BestStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='students', verbose_name='Аватар')),
                ('name', models.CharField(max_length=60, verbose_name='ФИО')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Достижения')),
            ],
            options={
                'verbose_name': 'Лучший студент',
                'verbose_name_plural': 'Лучшие студенты',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.CharField(max_length=60, verbose_name='Организатор')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='Время')),
                ('link', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название направления')),
                ('school', models.CharField(blank=True, max_length=80, null=True, verbose_name='Школа')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код направления')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Бюджетных мест')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена обучения')),
                ('jsons', models.JSONField(blank=True, null=True, verbose_name='Прочее')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logo', verbose_name='Логотип')),
                ('org_detail', models.TextField(blank=True, null=True, verbose_name='Код направления')),
                ('video_link', models.TextField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('plan', models.TextField(blank=True, null=True, verbose_name='Учебный план')),
                ('best_students', models.ManyToManyField(blank=True, to='api.BestStudent', verbose_name='Лучшие студенты')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.event', verbose_name='Вебинар')),
                ('offer', models.ManyToManyField(blank=True, related_name='_organization_offer_+', to='api.Organization', verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('status', models.CharField(choices=[('parent', 'Родитель'), ('enrollee', 'Абитуриент')], max_length=10, verbose_name='Статус')),
                ('SNILS', models.IntegerField(null=True, verbose_name='СНИЛС')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
