# Generated by Django 3.1.4 on 2021-01-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='jsons',
            field=models.JSONField(blank=True, null=True, verbose_name='Прочее'),
        ),
    ]
