# Generated by Django 3.1.4 on 2020-12-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номаер специальности'),
        ),
        migrations.AlterField(
            model_name='event',
            name='speciality',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Специальность'),
        ),
    ]
