# Generated by Django 3.1.4 on 2021-01-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('weekdays', 'Будни студента'), ('campus', 'Кампус ДВФУ'), ('events', 'Студенческие события'), ('premises', 'Учебные помещения'), ('library', 'Библиотека'), ('creative_center', 'Творческий центр'), ('sport_life', 'Спортивная жизнь студентов'), ('laboratories', 'Лаборатории'), ('center_nti', 'Центр НТИ'), ('international_activity', 'Международная деятельность')], max_length=30, verbose_name='Категория')),
                ('img', models.ImageField(blank=True, null=True, upload_to='gallery', verbose_name='Фото')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
