# Generated by Django 3.1.4 on 2020-12-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201218_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='offer',
        ),
        migrations.AddField(
            model_name='organization',
            name='offer',
            field=models.ManyToManyField(blank=True, null=True, related_name='_organization_offer_+', to='api.Organization', verbose_name='Предложение'),
        ),
    ]
