# Generated by Django 3.1.4 on 2021-01-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_organization_jsons'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='video_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
