# Generated by Django 3.1.4 on 2021-01-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('parent', 'Родитель'), ('enrollee', 'Абитуриент')], max_length=10, verbose_name='Статус')),
                ('name', models.CharField(max_length=60, verbose_name='Фио')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('number', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Авторизированный', 'verbose_name_plural': 'Авторизированные'},
        ),
    ]
