# Generated by Django 3.1.4 on 2020-12-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201219_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватар')),
                ('name', models.CharField(max_length=60, verbose_name='ФИО')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Достижения')),
            ],
            options={
                'verbose_name': 'Лучший студент',
                'verbose_name_plural': 'Лучшие студенты',
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Логотип')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('link', models.SlugField(unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Стажировка',
                'verbose_name_plural': 'Стажировки',
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Логотип')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('link', models.SlugField(unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Практика',
                'verbose_name_plural': 'Практики',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Логотип')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('link', models.SlugField(unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Трудоустройство',
                'verbose_name_plural': 'Трудоустройство',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Логотип'),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='best_students',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='internship',
        ),
        migrations.AlterField(
            model_name='organization',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код направления'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='offer',
            field=models.ManyToManyField(blank=True, related_name='_organization_offer_+', to='api.Organization', verbose_name='Предложение'),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='work',
        ),
        migrations.AddField(
            model_name='organization',
            name='best_students',
            field=models.ManyToManyField(blank=True, to='api.BestStudent', verbose_name='Лучшие студенты'),
        ),
        migrations.AddField(
            model_name='organization',
            name='internship',
            field=models.ManyToManyField(blank=True, to='api.Internship', verbose_name='Стажировки'),
        ),
        migrations.AddField(
            model_name='organization',
            name='practice',
            field=models.ManyToManyField(blank=True, to='api.Practice', verbose_name='Практики'),
        ),
        migrations.AddField(
            model_name='organization',
            name='work',
            field=models.ManyToManyField(blank=True, to='api.Work', verbose_name='Трудоустройства'),
        ),
    ]
