# Generated by Django 3.1.4 on 2021-01-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210107_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='org_logo', verbose_name='Логотип'),
        ),
    ]
