# Generated by Django 3.1.4 on 2020-12-19 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201219_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='work',
        ),
    ]
