# Generated by Django 3.1.4 on 2021-01-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210108_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='detail',
            new_name='org_detail',
        ),
    ]
