# Generated by Django 3.1.4 on 2020-12-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_organization_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='work',
            field=models.ManyToManyField(blank=True, to='api.Work', verbose_name='Трудоустройства'),
        ),
    ]
