# Generated by Django 3.1.4 on 2021-01-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210109_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='achievements', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='beststudent',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='students', verbose_name='Аватар'),
        ),
    ]
