# Generated by Django 3.1.4 on 2021-01-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210109_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.TextField(blank=True, null=True, verbose_name='Учебный план'),
        ),
    ]
