# Generated by Django 3.1.4 on 2020-12-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201222_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='USE',
        ),
    ]
