# Generated by Django 3.1.4 on 2020-12-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
